<Project Sdk="Microsoft.NET.Sdk">

  <!-- Section 6.4: the tool-calling loop written by hand, and human approval for consequential tools. -->
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\Northwind.Shared\Northwind.Shared.csproj" />
  </ItemGroup>

</Project>
